include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml

services:
  - docker:dind

stages:
  - test
  - runSphinx
  - deploy

test_cookiecutter_template:
  image: philippkohl/python-poetry:latest
  stage: test
  script:
    - poetry install
    - poetry run pytest --ignore="{{cookiecutter.project_folder}}"

run_sphinx:
  image: philippkohl/python-poetry:latest
  stage: runSphinx
  script:
    - startPath="$PWD"
    # Install cookiecutter and export path
    - pip install --user cookiecutter
    - export PATH=$HOME/.local/bin:$PATH
    - source ~/.profile
    # Cookiecutter installation end
    - poetry config virtualenvs.create false
    - source /opt/poetry/env
    - cd "$startPath"
    - cookiecutter --no-input . project_name="NLP Process Model" project_author="Philipp Kohl" project_author_email="p.kohl@fh-aachen.de"
    - cd nlp-process-model
    - poetry install --no-root
    - poetry run gen_doc
    - cd "$startPath"
  artifacts:
    paths:
      - nlp-process-model/docs/build/html/

pages:
  image: node:lts-slim
  stage: deploy
  script:
    - cp -R nlp-process-model/docs/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

