name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, feature/githubactions ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  test_cookiecutter_template:
    runs-on: ubuntu-latest
    container: philippkohl/python-poetry:latest
    steps:
      - uses: actions/checkout@v2
      - run: poetry install
      - run: poetry run pytest --ignore="{{cookiecutter.project_folder}}"

  run_sphinx:
    runs-on: ubuntu-latest
    container: philippkohl/python-poetry:latest
    steps:
      - uses: actions/checkout@v2
      - run: startPath="$PWD"
      # Install cookiecutter and export path
      - run: pip install --user cookiecutter
      - run: export PATH=$HOME/.local/bin:$PATH
      - run: source ~/.profile
      # Cookiecutter installation end
      - run: poetry config virtualenvs.create false
      - run: source /opt/poetry/env
      - run: cd "$startPath"
      - run: cookiecutter --no-input . project_name="NLP Process Model" project_author="Philipp Kohl" project_author_email="p.kohl@fh-aachen.de"
      - run: cd nlp-process-model
      - run: poetry install --no-root
      - run: poetry run gen_doc
      - run: cd "$startPath"
      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: nlp-process-model/docs/build/html/


