name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, feature/githubactions ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
	test_cookiecutter_template:
	  container: philippkohl/python-poetry:latest
	  steps:
		- poetry install
		- poetry run pytest --ignore="{{cookiecutter.project_folder}}"

	run_sphinx:
	  container: philippkohl/python-poetry:latest
	  steps:
		- startPath="$PWD"
		# Install cookiecutter and export path
		- pip install --user cookiecutter
		- export PATH=$HOME/.local/bin:$PATH
		- source ~/.profile
		# Cookiecutter installation end
		- poetry config virtualenvs.create false
		- source /opt/poetry/env
		- cd "$startPath"
		- cookiecutter --no-input . project_name="NLP Process Model" project_author="Philipp Kohl" project_author_email="p.kohl@fh-aachen.de"
		- cd nlp-process-model
		- poetry install --no-root
		- poetry run gen_doc
		- cd "$startPath"
	  - name: Upload documentation
  		uses: actions/upload-artifact@v2
  		with:
    		name: documentation
    		path: nlp-process-model/docs/build/html/


